version: '2.1'

networks:
  keycloak-network:

#volumes:
#  keycloak-nginx-letsencrypt-ssl:

services:
  keycloak:
    image: "quay.io/keycloak/keycloak:12.0.4"
    container_name: keycloak
    networks:
      - keycloak-network
    environment:
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    restart: unless-stopped
  nginx:
    image: lokios/keycloak-nginx-lets-encrypt:certbot_v1.11
    container_name: nginx
    networks:
      - keycloak-network
    depends_on:
      - keycloak
    volumes:
      - ./keycloak-nginx-letsencrypt-ssl:/etc/letsencrypt
    environment:
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_DOMAIN=www.example.com
      - LE_EMAIL="admin@example.com"
      - LE_OPTIONS="--debug-challenges"
      - LE_RENEW_OPTIONS
      - LE_RENEW_CRON_COMMAND
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
